services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CPSIT\FrontendAssetHandler\Command\InitConfigCommand:
    arguments:
      $initSteps:
        - '@CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyStep'
        - '@CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyInteractiveStep'

  CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyDecisionMaker:
  CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyHandler:
  CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyInteractiveStep:
  CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyProvider:
  CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyProcessor:
  CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyRevisionProvider:
  CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyStep:
