services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyDecisionMaker:
  CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyHandler:
  CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyProvider:
  CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyProcessor:
  CPSIT\FrontendAssetHandler\Tests\Unit\Fixtures\Classes\DummyRevisionProvider:
